# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Test

    # Do it on github's own repo, this action is very simple and takes no time
    runs-on: ubuntu-latest

    steps:
      - name: Nothing really
        run: echo hello
